name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pypi-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4.0.0

      # Extract version from release tag, or fall back to manual input
      - name: Determine version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION=$(poetry version -s)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing version $VERSION"

      - name: Configure PyPI credentials
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_PASSWORD }}"

      - name: Build and publish to PyPI
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          poetry version $VERSION
          poetry publish --build
